Repository E3SM-Project/E3SM, pull requests merged in 2018-12, with the labels that each got.

#2649 Fix 20th-century transient BGC use case specification
  components/cam/cime_config/config_component.xml
Labels: Atmosphere, For maint-1.1, bug fix PR, compset

#2651 Update test names for BGC cases
  cime/config/e3sm/tests.py
Labels: BFB

#2653 Updates finidat for tsc and pgn test
  cime/scripts/lib/CIME/SystemTests/pgn.py
  cime/scripts/lib/CIME/SystemTests/tsc.py
Labels: BFB, Scripts, Testing

#2639 Update the MOSART 1/8th degree global parameter file
  components/mosart/bld/namelist_files/namelist_defaults_mosart.xml
Labels: NML, River, non-BFB

#2659 Update melvin openmpi
  cime/config/e3sm/machines/config_machines.xml
Labels: BFB, CIME, Machine Files

#2662 Reorders code to allow writing PGN cloud in the run phase
  cime/scripts/lib/CIME/SystemTests/pgn.py
Labels: BFB, Testing

#2660 Allow cpu overloading for MPI for melvin
  cime/config/e3sm/machines/config_machines.xml
Labels: BFB, CIME, Machine Files

#2664 Changes file name of cloud file so that bless script can copy it
  cime/scripts/lib/CIME/SystemTests/pgn.py
Labels: BFB, Testing
