Repository E3SM-Project/E3SM, pull requests merged in 2018-05, with the labels that each got.

#2312 Fix a typo in LICENSE
  LICENSE
Labels: BFB, For maint-1.0

#2315 Summit updates to fix runtime errors and env changes.
  cime/config/e3sm/machines/config_batch.xml
  cime/config/e3sm/machines/config_machines.xml
Labels: BFB, Machine Files, Summit

#1983 removing obsolete "compute_ppm_grids_old"
  components/homme/src/share/vertremap_base.F90
Labels: Atmosphere, HOMME, non-BFB, postV1

#2173 fix some memory leaks
  components/homme/src/share/edge_mod_base.F90
  components/homme/src/share/ll_mod.F90
  components/homme/src/share/metagraph_mod.F90
  components/homme/src/share/prim_driver_base.F90
  components/homme/src/share/schedule_mod.F90
  components/homme/src/share/spacecurve_mod.F90
Labels: HOMME, enhancement, postV1

#2276 Use approved CIME case value for threadedness check
  components/cam/cime_config/buildnml
Labels: Atmosphere, BFB, postV1

#2326 Build namelist one more time to make sure *_in files are updated
  run_e3sm.template.csh
Labels: BFB

#2340 Update grid name of ne30-wcycl pelayout on Theta
  cime/config/e3sm/allactive/config_pesall.xml
Labels: Theta

#2335 First steps towards pythonizing cam buildnml scripts
  components/cam/cime_config/buildnml
Labels: Atmosphere, BFB, Scripts

#2342 First steps towards pythonizing clm buildnml scripts
  components/clm/cime_config/buildnml
Labels: BFB, Land, Scripts

#2348 wait_for_tests: Need to watch out for strange characters in TestStatu…
  cime/scripts/lib/CIME/wait_for_tests.py
Labels: BFB, CIME, Scripts

#2350 tweaks to homme.py to properly run HOMME tests
  cime/scripts/lib/CIME/SystemTests/homme.py
Labels: BFB, CIME, Scripts

#2347 Pythonize mosart buildnml
  components/mosart/cime_config/buildnml
Labels: BFB, River, Scripts

#2354 Update queue node counts on Theta
  .gitignore
  cime/config/e3sm/allactive/config_pesall.xml
  cime/config/e3sm/testmods_dirs/allactive/mach/pet/shell_commands
  cime/config/e3sm/testmods_dirs/allactive/v1cmip6/shell_commands
Labels: BFB, Theta

#2313 Makes default the post deck bug fixes enabled via CPP for 1950 compsets
  components/cam/cime_config/config_component.xml
  components/cam/src/physics/cosp/MODIS_simulator/modis_simulator.F90
  components/cam/src/physics/rrtmg/ext/rrtmg_lw/rrtmg_lw_setcoef.f90
  components/cam/src/physics/rrtmg/ext/rrtmg_mcica/rrtmg_sw_spcvmc.f90
  components/cam/src/physics/rrtmg/ext/rrtmg_sw/rrtmg_sw_reftra.f90
  components/cam/src/physics/rrtmg/ext/rrtmg_sw/rrtmg_sw_setcoef.f90
  components/clm/cime_config/config_component.xml
  components/clm/src/biogeophys/BalanceCheckMod.F90
  components/clm/src/biogeophys/CanopyHydrologyMod.F90
  components/clm/src/biogeophys/EnergyFluxType.F90
  components/clm/src/biogeophys/SnowHydrologyMod.F90
  components/clm/src/biogeophys/SoilFluxesMod.F90
  components/clm/src/biogeophys/SoilTemperatureMod.F90
  components/clm/src/biogeophys/SurfaceAlbedoMod.F90
  components/clm/src/biogeophys/SurfaceRadiationMod.F90
Labels: Atmosphere, Land, bug fix PR, non-BFB

#2360 Increase pes for bgc on sandiatoss3
  cime/config/e3sm/allactive/config_pesall.xml
Labels: CIME, Machine Files

#2372 Update pelayouts of tests on Theta
  cime/config/e3sm/allactive/config_pesall.xml
  cime/config/e3sm/testmods_dirs/allactive/mach/pet/shell_commands
  cime/config/e3sm/testmods_dirs/allactive/v1cmip6/shell_commands
Labels: BFB, Machine Files, Theta

#2361 Update points file for mpas-seaice BGC EC60to30v3 configuration
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Sea Ice

#2373 Remove remaining xmlquery calls from build-namelist scripts
  components/mpas-albany-landice/bld/build-namelist
  components/mpas-albany-landice/cime_config/buildnml
  components/mpas-ocean/bld/build-namelist
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/build-namelist
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Scripts

#2375 Ignore unicode chars from command output
  cime/scripts/lib/CIME/utils.py
Labels: BFB, CIME, Scripts, bug fix PR
