Repository E3SM-Project/E3SM, pull requests merged in 2019-12, with the labels that each got.

#3287 NA RRM tri-grid support for F2010SC5-CMIP6 compset
  components/cam/bld/namelist_files/use_cases/2010S_cam5_CMIP6.xml
  components/clm/bld/namelist_files/use_cases/2010_CMIP6_control.xml
Labels: Atmosphere, Land, compset

#3332 Turn off O3 dry deposition in F2010SC5-CMIP6 compset
  components/cam/bld/namelist_files/use_cases/2010S_cam5_CMIP6.xml
Labels: Atmosphere, compset, non-BFB

#3278 fix bugs that cause two land output variables to be NaN
  components/clm/src/data_types/VegetationDataType.F90
Labels: BFB, Land, bug fix PR

#3318 Initialize SH_FLXPRC/SH_FLXSNW arrays for shallow convection
  components/cam/src/physics/cam/convect_shallow.F90
Labels: Atmosphere, BFB, bug fix PR

#3345 fix python rounding issue
  cime/scripts/lib/CIME/XML/env_batch.py
Labels: BFB, Scripts, bug fix PR

#3334 LDFLAGS should not be added via target_link_libraries
  components/cmake/build_model.cmake
  components/cmake/common_setup.cmake
Labels: BFB, CIME, bug fix PR

#3348 Fix component-specific cleaning
  cime/scripts/lib/CIME/build.py
Labels: BFB, CIME, bug fix PR

#3357 Change cdash project from ACME_Climate to E3SM
  cime/scripts/lib/CIME/wait_for_tests.py
Labels: BFB, CIME

#3350 Fix Depends-file usage for legacy build system
  cime/scripts/lib/CIME/BuildTools/configure.py
Labels: BFB, CIME, Scripts, bug fix PR

#3302 Make DYN_OMEGA consistent with theta dycore
  components/cam/src/dynamics/se/stepon.F90
Labels: Atmosphere, HOMME

#3359 Clean up use of LDFLAGS in config_compilers.xml
  cime/config/e3sm/machines/config_compilers.xml
Labels: CIME, Machine Files, bug fix PR

#3274 Update clubb to print tunable parameters and make TTEND consistent
  components/cam/src/physics/cam/clubb_intr.F90
Labels: Atmosphere, BFB

#3362 Change cdash project from ACME_Climate to E3SM
  cime/scripts/lib/CIME/wait_for_tests.py
Labels: BFB, CIME, Scripts

#3271 Fixing bug in theta NH restart
  components/cam/src/dynamics/se/restart_dynamics.F90
Labels: Atmosphere, bug fix PR

#3363 Fix preqx_kokkos/HOMMEBFB
  components/homme/src/preqx_kokkos/CMakeLists.txt
Labels: HOMME

#3275 Update F20TRC5-CMIP6 SST and sea ice settings
  cime/src/components/data_comps/docn/cime_config/config_component.xml
Labels: Atmosphere, compset

#3349 Add ATM2ROF maps for ne120np4 to r0125
  cime/config/e3sm/config_grids.xml
Labels: BFB, NML, Scripts, Testing, bug fix PR

#3338 Fix F2010SC5-CMIP6.northamericax4v1_r0125_northamericax4v1
  cime/src/drivers/mct/main/cime_comp_mod.F90
Labels: Atmosphere
