Repository E3SM-Project/E3SM, pull requests merged in 2020-09, with the labels that each got.

#3805 Fixes default compute interval for heat budget
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
Labels: BFB, NML, Ocean

#3743 fix DYN_PS output
  components/cam/src/dynamics/se/stepon.F90
Labels: Atmosphere, HOMME

#3773 Make one of homme targets noio
  components/homme/src/share/prim_driver_base.F90
  components/homme/test_execs/stt/CMakeLists.txt
Labels: HOMME standalone

#3764 add support for hydrostatic mode even when using IMEX timestepping
  components/homme/src/theta-l/imex_mod.F90
Labels: HOMME

#3759 Enable DCAPE or ULL to be used alone
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/physics/cam/physpkg.F90
  components/cam/src/physics/cam/zm_conv.F90
  components/cam/src/physics/cam/zm_conv_intr.F90
Labels: Atmosphere, BFB, enhancement

#3814 Updated CLUBBv2 paramters and flags
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/physics/cam/clubb_intr.F90
  components/cam/src/physics/clubb/advance_clubb_core_module.F90
  components/cam/src/physics/clubb/advance_xm_wpxp_module.F90
  components/cam/src/physics/clubb/model_flags.F90
  components/cam/src/physics/clubb/parameter_indices.F90
  components/cam/src/physics/clubb/parameters_tunable.F90
Labels: Atmosphere, BFB, NML

#3794 Minimum droplet number conc. option and cleanup
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
  components/cam/bld/namelist_files/namelist_definition.xml
  components/cam/src/physics/cam/micro_mg2_0.F90
  components/cam/src/physics/cam/micro_mg_cam.F90
Labels: Atmosphere, non-BFB

#3807 Add support for ECwISC30to60E1r2 MPAS-Ocean/Seaice grid
  cime_config/config_grids.xml
  components/clm/bld/namelist_files/namelist_definition_clm4_5.xml
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Ocean, Sea Ice, enhancement

#3709 Fixes inline interpolation of land initial condition
  components/clm/src/main/initInterp.F90
Labels: BFB, Land, bug fix PR

#3819 Script support for new EC30to60E2r2 ocean mesh
  cime_config/allactive/config_pesall.xml
  cime_config/config_grids.xml
  components/clm/bld/namelist_files/namelist_definition_clm4_5.xml
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Coupled Model, Scripts

#3824 Fix MMF History Variables
  components/cam/cime_config/testdefs/testmods_dirs/cam/crmout/user_nl_cam
  components/cam/src/physics/crm/crm_history.F90
  components/cam/src/physics/crm/crm_output_module.F90
  components/cam/src/physics/crm/crm_physics.F90
  components/cam/src/physics/crm/sam/crm_module.F90
  components/cam/src/physics/crm/samxx/cpp_interface_mod.F90
  components/cam/src/physics/crm/samxx/crm.cpp
  components/cam/src/physics/crm/samxx/fortran/crm_module.F90
  components/cam/src/physics/crm/samxx/fortran/crm_output_module.F90
  components/cam/src/physics/crm/samxx/post_timeloop.cpp
  components/cam/src/physics/crm/samxx/pre_timeloop.cpp
  components/cam/src/physics/crm/samxx/test/cpp_driver.F90
  components/cam/src/physics/crm/samxx/test/fortran_driver.F90
  components/cam/src/physics/crm/samxx/timeloop.cpp
  components/cam/src/physics/crm/samxx/vars.cpp
  components/cam/src/physics/crm/samxx/vars.h
Labels: Atmosphere, MMF

#3798 Three small BFB fixes.
  components/homme/src/share/bndry_mod_base.F90
  components/homme/src/share/gllfvremap_mod.F90
  components/homme/src/share/sl_advection.F90
Labels: BFB, HOMME, bug fix PR

#3828 Enable E3SM on Tulip
  cime_config/machines/config_batch.xml
  cime_config/machines/config_compilers.xml
  cime_config/machines/config_machines.xml
Labels: BFB, Machine Files

#3802 Add MPAS-Seaice files for OpenMP or OpenACC offload
  cime_config/machines/Depends.ibmgpu.cmake
  cime_config/machines/Depends.pgigpu
  cime_config/machines/Depends.pgigpu.cmake
  cime_config/machines/config_machines.xml
Labels: BFB, Sea Ice, Summit, performance

#3836 Replace CLM with ELM in a few pelayout entires
  cime_config/allactive/config_pesall.xml
Labels: CIME, bug fix PR

#3813 Adding dam construction year to MOSART Water Management scheme
  components/mosart/bld/build-namelist
  components/mosart/bld/namelist_files/namelist_defaults_mosart.xml
  components/mosart/bld/namelist_files/namelist_definition_mosart.xml
  components/mosart/src/wrm/WRM_modules.F90
  components/mosart/src/wrm/WRM_subw_IO_mod.F90
  components/mosart/src/wrm/WRM_type_mod.F90
Labels: BFB, River

#3834 Change remove "_p" from area/lat/lon output variables
  components/cam/src/dynamics/se/dyn_grid.F90
Labels: Atmosphere

#3765 Addition of daily sea ice output option consistent with E3SM HR and switch to single precision
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Coupled Model, Sea Ice, enhancement

#3841 EAM: Remove Q from cam/dynamics/se restart.
  components/cam/src/dynamics/se/restart_dynamics.F90
  components/homme/src/share/sl_advection.F90
Labels: Atmosphere, HOMME, enhancement

#3843 Update compy L pe-layout for trigrid with EC30to60
  cime_config/allactive/config_pesall.xml
Labels: BFB, Compy, Coupled Model, enhancement

#3781 Integrate with Travis CI and the E3SM singularity container
  .travis.yml
  .travis/run.sh
  .travis/setup.sh
Labels: Testing

#3851 Improve Travis debugging
  .travis/run.sh
Labels: BFB, Testing

#3846 Switch on sea ice defaults and snicar on lnd to match snow on sea ice
  components/elm/bld/CLMBuildNamelist.pm
  components/elm/bld/namelist_files/namelist_defaults_clm4_5.xml
  components/elm/bld/namelist_files/namelist_definition_clm4_5.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
Labels: Coupled Model, Land, NML, Sea Ice, non-BFB

#3735 Adds reservoir stratification to MOSART-heat
  components/elm/src/cpl/clm_cpl_indices.F90
  components/elm/src/cpl/lnd_import_export.F90
  components/elm/src/main/lnd2atmMod.F90
  components/elm/src/main/lnd2atmType.F90
  components/mosart/bld/build-namelist
  components/mosart/bld/namelist_files/namelist_defaults_mosart.xml
  components/mosart/bld/namelist_files/namelist_definition_mosart.xml
  components/mosart/src/cpl/rof_comp_esmf.F90
  components/mosart/src/cpl/rof_comp_mct.F90
  components/mosart/src/cpl/rof_cpl_indices.F90
  components/mosart/src/riverroute/MOSART_physics_mod.F90
  components/mosart/src/riverroute/MOSART_stra_mod.F90
  components/mosart/src/riverroute/RtmHistFlds.F90
  components/mosart/src/riverroute/RtmMod.F90
  components/mosart/src/riverroute/RtmVar.F90
  components/mosart/src/riverroute/RunoffMod.F90
  components/mosart/src/wrm/WRM_subw_IO_mod.F90
  components/mosart/src/wrm/WRM_type_mod.F90
Labels: BFB, River
