Repository E3SM-Project/E3SM, pull requests merged in 2020-05, with the labels that each got.

#3557 Copy changes from standalone CIME to shr_mem_mod
  cime/src/share/util/shr_mem_mod.F90
Labels: BFB, CIME

#3549 EAM: ne0np4_northamericax4v1.pg2_r0125_ne0np4_northamericax4v1.pg2 config
  cime/config/e3sm/config_grids.xml
  components/cam/bld/config_files/horiz_grid.xml
  components/cam/bld/namelist_files/namelist_defaults_cam.xml
Labels: Atmosphere, BFB

#3562 Enable COSP with RRTMGP
  components/cam/src/physics/rrtmg/radiation.F90
  components/cam/src/physics/rrtmgp/cam_optics.F90
  components/cam/src/physics/rrtmgp/radconstants.F90
  components/cam/src/physics/rrtmgp/radiation.F90
Labels: Atmosphere, BFB

#3552 Fix RRTMGP for MMF
  cime/config/e3sm/tests.py
  components/cam/src/physics/crm/rrtmgp/radiation.F90
Labels: Atmosphere, MMF

#3567 Physgrid and SL3D cleanups
  cime/config/e3sm/tests.py
  components/cam/src/dynamics/se/dp_coupling.F90
  components/cam/src/dynamics/se/dyn_grid.F90
  components/cam/src/dynamics/se/fv_physics_coupling_mod.F90
  components/cam/src/dynamics/se/gravity_waves_sources.F90
  components/cam/src/dynamics/se/inidat.F90
  components/homme/src/interpolate_driver_mod.F90
  components/homme/src/share/cube_mod.F90
  components/homme/src/share/gllfvremap_mod.F90
  components/homme/src/share/prim_driver_base.F90
  components/homme/src/share/sl_advection.F90
  components/homme/src/share/vertremap_base.F90
  components/homme/src/test_src/dcmip16_wrapper.F90
  components/homme/test/reg_test/namelists/thetah-sl-dcmip16_test1pg2.nl
  components/homme/test/reg_test/run_tests/test-list.cmake
  components/homme/test/reg_test/run_tests/thetah-sl-dcmip16_test1pg2.cmake
Labels: Atmosphere, HOMME, non-BFB

#3583 Homme: Fix a restart bug.
  components/cam/src/dynamics/se/restart_dynamics.F90
Labels: Atmosphere, HOMME, bug fix PR

#3575 Fix ftype1 in NH theta
  components/cam/src/dynamics/se/stepon.F90
  components/homme/src/theta-l/prim_advance_mod.F90
Labels: Atmosphere, bug fix PR, non-BFB

#3548 Remove native_mapping functionality from files in cam/src/dynamics/se
  components/cam/src/dynamics/se/dyn_comp.F90
  components/cam/src/dynamics/se/native_mapping.F90
Labels: Atmosphere, BFB, HOMME

#3578 Modifies chem pp optimization level from O2 to O1 for PGI compilers
  components/cam/chem_proc/src/Makefile
Labels: Atmosphere, BFB, Chemistry Pre-Processor

#3581 Update MMF radiation_tend for cam_optics changes
  cime/config/e3sm/tests.py
  components/cam/src/physics/crm/rrtmgp/radiation.F90
Labels: Atmosphere, MMF

#3600 sandiatoss3: Update netcdf and hdf5 modules
  cime/config/e3sm/machines/config_machines.xml
Labels: BFB, CIME, Machine Files

#3601 Add support for OpenMPI on anlworkstation
  cime/config/e3sm/machines/config_compilers.xml
  cime/config/e3sm/machines/config_machines.xml
  cime/config/xml_schemas/config_compilers_v2.xsd
  cime/scripts/Tools/Makefile
Labels: BFB, CIME, Machine Files, SCORPIO

#3525 Set io_type to ocn_pio_typename for all streams that were not set
  components/mpas-ocean/cime_config/buildnml
Labels: Ocean, Scripts

#3571 Fix issue with unallocated elem structure in dynamics initialization
  components/cam/src/dynamics/se/dyn_comp.F90
Labels: Atmosphere, BFB, HOMME, bug fix PR

#3554 Update machine settings for LANL machines grizzly and badger
  cime/config/e3sm/machines/config_compilers.xml
  cime/config/e3sm/machines/config_machines.xml
Labels: Machine Files

#3607 Ensure sync is called before freedecomp
  components/cice/src/drivers/cpl/ice_history_write.F90
Labels: Sea Ice, bug fix PR

#3526 Adds wsubmin namelist parameter to gustiness use case
  components/cam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2_gust.xml
  components/cam/cime_config/testdefs/testmods_dirs/cam/gust_param/shell_commands
  components/cam/cime_config/testdefs/testmods_dirs/cam/gust_param/user_nl_cam
Labels: Atmosphere, non-BFB
