Repository E3SM-Project/E3SM, pull requests merged in 2020-10, with the labels that each got.

#3475 Update fields in ocean monthly output
  components/mpas-ocean/cime_config/buildnml
Labels: BFB, Ocean

#3857 Sea ice model output for E3SM V2
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Coupled Model, NML, Sea Ice

#3868 Allows crops of to be put on separate land units
  components/elm/bld/CLMBuildNamelist.pm
  components/elm/src/main/controlMod.F90
  components/elm/src/main/initGridCellsMod.F90
  components/elm/src/main/surfrdMod.F90
  components/elm/src/main/surfrdUtilsMod.F90
Labels: BFB, Land

#3872 Finish moving cam to eam
  components/eam/src/physics/crm/samxx/test/build/summit_cpu_pgi.sh
  components/eam/src/physics/crm/samxx/test/perf_mod.F90
  components/eam/src/physics/crm/samxx/test/shr_const_mod.F90
Labels: Atmosphere, MMF

#3755 Plant hydraulics restart
  components/elm/src/biogeophys/SoilStateType.F90
Labels: BFB, Land

#3873 Update ICG file datestamps for EC30to60E2r2 and e3sm_prod
  cime_config/tests.py
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Coupled Model, Ocean, Scripts, Sea Ice

#3847 Add script support for new ocn/ice WC14to60E2r3 grid
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_definition_clm4_5.xml
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Coupled Model, Ocean, RRM, Scripts

#3863 Deallocate local vector that is not deallocated automatically
  components/eam/src/cpl/atm_comp_mct.F90
Labels: Atmosphere, bug fix PR

#3869 Add theta-SL-pg2 config for EAM Antarctica RRM
  cime_config/config_grids.xml
  components/eam/bld/config_files/horiz_grid.xml
  components/eam/bld/namelist_files/namelist_defaults_cam.xml
Labels: Atmosphere, compset

#3840 Change options for homme anvil and sandiatoss3 bfb runs
  cime_config/tests.py
  components/homme/cmake/machineFiles/anvil-bfb.cmake
  components/homme/cmake/machineFiles/sandiatoss3-bfb.cmake
  components/homme/cmake/machineFiles/sandiatoss3.cmake
Labels: HOMME

#3860 Allow up to 10 atm history tapes
  components/eam/bld/namelist_files/namelist_definition.xml
Labels: Atmosphere, BFB, NML

#3876 Update mapping and domain files for EC30to60E2r2 grid
  cime_config/config_grids.xml
Labels: Coupled Model, Ocean, Scripts, Sea Ice, non-BFB

#3871 Update global attributes for EAM, ELM and MOSART
  components/eam/src/control/cam_history.F90
  components/eam/src/control/filenames.F90
  components/eam/src/cpl/atm_comp_mct.F90
  components/elm/src/main/histFileMod.F90
  components/mosart/src/riverroute/RtmHistFile.F90
  components/mosart/src/riverroute/RtmVar.F90
Labels: Atmosphere, BFB, Land, River

#3878 Define default pe-layout for T62_oEC60to30v3 DTESTM on sandiatoss3
  cime_config/allactive/config_pesall.xml
Labels: Scripts, Testing

#3882 Add additional diagnostic outputs to track SSW events
  components/eam/src/physics/cam/cam_diagnostics.F90
Labels: Atmosphere, BFB

#3763 update path to cprnc on Cori
  components/homme/cmake/machineFiles/cori-knl.cmake
Labels: Cori, HOMME standalone

#3889 Fix for unused kokkos in mpas
  components/cmake/build_mpas_model.cmake
Labels: Atmosphere, HOMME

#3865 Increase field widths in atm_chunk_cost.txt
  components/eam/src/physics/cam/phys_grid.F90
Labels: Atmosphere

#3856 Initial commit to prepend casename to mpas output files
  components/mpas-albany-landice/cime_config/buildnml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/cime_config/buildnml
Labels: BFB, Land Ice, Ocean, Sea Ice, enhancement

#3885 Fixes a bug in dry size calculations and these calculations now use current state
  components/eam/src/chemistry/modal_aero/aero_model.F90
  components/eam/src/chemistry/utils/modal_aero_calcsize.F90
  components/eam/src/chemistry/utils/modal_aero_wateruptake.F90
  components/eam/src/physics/cam/aer_rad_props.F90
  components/eam/src/physics/cam/modal_aer_opt.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/rad_constituents.F90
  components/eam/src/physics/crm/physpkg.F90
  components/eam/src/physics/crm/rrtmgp/radiation.F90
  components/eam/src/physics/rrtmg/radiation.F90
  components/eam/src/physics/rrtmgp/cam_optics.F90
  components/eam/src/physics/rrtmgp/radiation.F90
Labels: Atmosphere, non-BFB

#3896 Mass test: Double tol on CO2_FF global mass based on compy_pgi change.
  components/homme/utils/e3sm_test/check_mass_conservation.py
Labels: Atmosphere, BFB, PGI, Testing, bug fix PR

#3892 Machine file changes for PNNL's Sooty
  cime_config/machines/config_compilers.xml
  cime_config/machines/config_machines.xml
  cime_config/machines/config_pio.xml
Labels: Machine Files

#3900 Defense against use of user_nl_cam/user_nl_clm after name changes
  cime_config/testmods_dirs/allactive/v1cmip6/user_nl_eam
  components/eam/cime_config/buildnml
  components/elm/cime_config/buildnml
Labels: Atmosphere, BFB

#3917 Add user_nl_mpassi for elm bgcexp testmod in order to pass automated tests
  components/elm/cime_config/testdefs/testmods_dirs/elm/bgcexp/user_nl_mpassi
Labels: BGC, Land, Testing, bug fix PR
