Repository E3SM-Project/E3SM, pull requests merged in 2021-09, with the labels that each got.

#4506 Fix path for SOwISC12to60E2r4 grid domain file
  cime_config/config_grids.xml
Labels: mpas-ocean, mpas-seaice, Scripts, BFB

#4486 Expanding OpenACC to encompass all of diagnostics routine
  components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F
  components/mpas-ocean/src/shared/mpas_ocn_equation_of_state.F
  components/mpas-ocean/src/shared/mpas_ocn_equation_of_state_jm.F
  components/mpas-ocean/src/shared/mpas_ocn_equation_of_state_linear.F
  components/mpas-ocean/src/shared/mpas_ocn_equation_of_state_wright.F
  components/mpas-ocean/src/shared/mpas_ocn_mesh.F
  components/mpas-ocean/src/shared/mpas_ocn_tidal_forcing.F
Labels: mpas-ocean, BFB

#4503 Add initial HOMME cmake machinefiles for perlmutter and cori-gpu.
  components/homme/cmake/machineFiles/cori-gpu-nocuda-nvidia.cmake
  components/homme/cmake/machineFiles/cori-gpu-nvidia.cmake
  components/homme/cmake/machineFiles/perlmutter-gnu.cmake
  components/homme/cmake/machineFiles/perlmutter-nocuda-gnu.cmake
  components/homme/cmake/machineFiles/perlmutter-nocuda-nvidia.cmake
  components/homme/cmake/machineFiles/perlmutter-nvidia.cmake
Labels: Machine Files, HOMME standalone

#4455 Replace run_e3sm template
  run_e3sm.template.csh
  run_e3sm.template.sh
Labels: run_e3sm

#4384 Remove LANDM_COSLAT and replace uses with LANDFRAC
  components/eam/src/dynamics/se/dyn_comp.F90
  components/eam/src/physics/cam/cldwat.F90
  components/eam/src/physics/cam/comsrf.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/pkg_cld_sediment.F90
  components/eam/src/physics/cam/pkg_cldoptics.F90
  components/eam/src/physics/cam/radiation_data.F90
  components/eam/src/physics/cam/restart_physics.F90
  components/eam/src/physics/cam/stratiform.F90
  components/eam/src/physics/crm/physpkg.F90
  components/eam/src/physics/crm/rrtmg/radiation.F90
  components/eam/src/physics/crm/rrtmgp/radiation.F90
  components/eam/src/physics/rrtmg/radiation.F90
  components/eam/src/physics/rrtmgp/radiation.F90
  components/eam/tools/topo_tool/bin_to_cube/README
  components/eam/tools/topo_tool/bin_to_cube/bin_to_cube.F90
  components/eam/tools/topo_tool/cube_to_target/cube_to_target.F90
Labels: Atmosphere, non-BFB, MMF

#4467 Remove deprecated MPAS grids from E3SM scripts
  cime_config/allactive/config_pesall.xml
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
  components/mpas-seaice/cime_config/buildnml
  driver-mct/cime_config/config_component_e3sm.xml
  driver-moab/cime_config/config_component_e3sm.xml
Labels: mpas-ocean, mpas-seaice, Scripts, BFB, Coupled Model

#4473 Update builds on Ascent
  cime_config/allactive/config_pesall.xml
  cime_config/machines/Depends.ascent.cmake
  cime_config/machines/Depends.pgi.cmake
  cime_config/machines/Depends.pgigpu.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_compilers.xml
  cime_config/machines/config_machines.xml
  cime_config/tests.py
  components/eam/cime_config/testdefs/testmods_dirs/eam/single_thread/shell_commands
Labels: Machine Files, BFB, Summit, Testing, IBM

#4515 Zeroed out dummy ocean concentrations of aerosols
  components/mpas-seaice/driver/ice_comp_mct.F
Labels: mpas-ocean, mpas-seaice, bug fix PR, BFB, BGC

#4508 Add backup HTTP server with Singularity source tarball
  .circleci/container.sh
  .circleci/setup.sh
Labels: Testing

#4524 Align sea ice settings of SOwISC12to60E2 and WCAtl12to45E2 with WC14to60
  components/mpas-seaice/bld/namelist_files/namelist_defaults_mpassi.xml
Labels: mpas-seaice, BFB, Coupled Model, RRM

#4526 Fix CIMEROOTs for buildnml scripts
  cime_config/machines/config_machines.xml
  components/data_comps/datm/cime_config/buildnml
  components/data_comps/desp/cime_config/buildnml
  components/data_comps/dice/cime_config/buildnml
  components/data_comps/dlnd/cime_config/buildnml
  components/data_comps/docn/cime_config/buildnml
  components/data_comps/drof/cime_config/buildnml
  components/data_comps/dwav/cime_config/buildnml
  components/xcpl_comps/xatm/cime_config/buildnml
  components/xcpl_comps/xglc/cime_config/buildnml
  components/xcpl_comps/xice/cime_config/buildnml
  components/xcpl_comps/xlnd/cime_config/buildnml
  components/xcpl_comps/xocn/cime_config/buildnml
  components/xcpl_comps/xrof/cime_config/buildnml
  components/xcpl_comps/xwav/cime_config/buildnml
  driver-mct/cime_config/buildnml
  driver-mct/unit_test/CMakeLists.txt
  driver-moab/cime_config/buildnml
Labels: BFB, CIME

#4528 Fix the CircleCI script that installs Singularity
  .circleci/setup.sh
Labels: Testing

#4476 Push chunk loop into crm_physics()
  components/eam/src/physics/crm/crm_ecpp_output_module.F90
  components/eam/src/physics/crm/crm_history.F90
  components/eam/src/physics/crm/crm_physics.F90
  components/eam/src/physics/crm/physpkg.F90
  components/eam/src/physics/crm/sam/crm_module.F90
  components/eam/src/physics/crm/samomp/crm_module.F90
Labels: Atmosphere, MMF

#4488 Update and clean-up compsets for use in test suites
  cime_config/allactive/config_compsets.xml
  cime_config/config_grids.xml
  cime_config/tests.py
  components/eam/bld/namelist_files/use_cases/1850-2005_cam4.xml
  components/eam/bld/namelist_files/use_cases/1850-2005_cam4_bgc.xml
  components/eam/bld/namelist_files/use_cases/1850-2005_cam4_super_fast_llnl.xml
  components/eam/bld/namelist_files/use_cases/1850_cam5_av1c-04p2.xml
  components/eam/bld/namelist_files/use_cases/2000_cam4_super_fast_llnl.xml
  components/eam/bld/namelist_files/use_cases/2000_cam4_trop_chem.xml
  components/eam/bld/namelist_files/use_cases/2000_cam4_trop_strat_soa.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2-MMF-1mom.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2-MMF-2mom.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2_bgc.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-04p2_gust.xml
  components/eam/bld/namelist_files/use_cases/2000_cam5_av1c-h01a.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp26.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp45.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp45_bgc.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp60.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp85.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp85_bgc.xml
  components/eam/bld/namelist_files/use_cases/2005-2100_cam4_rcp85v2.xml
  components/eam/bld/namelist_files/use_cases/2005_cam4.xml
  components/eam/bld/namelist_files/use_cases/2010_mmf_1mom.xml
  components/eam/bld/namelist_files/use_cases/2010_mmf_2mom.xml
  components/eam/bld/namelist_files/use_cases/20TR_cam5_av1c-04p2.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_cam3.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_cam4.xml
  components/eam/bld/namelist_files/use_cases/aquaplanet_cam5.xml
  components/eam/bld/namelist_files/use_cases/cam3.xml
  components/eam/bld/namelist_files/use_cases/cam4_bam_radpsv_geos5.xml
  components/eam/bld/namelist_files/use_cases/cam4_chem_radpsv_geos5.xml
  components/eam/bld/namelist_files/use_cases/cam4_trop_strat_chem.xml
  components/eam/bld/namelist_files/use_cases/sd_cam4_trop_strat_soa.xml
  components/eam/bld/namelist_files/use_cases/waccm_1850-2005_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccm_1850_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccm_1955-2005_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccm_1974-2005_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccm_2000_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccm_2005-2100_cam4_rcp26.xml
  components/eam/bld/namelist_files/use_cases/waccm_2005-2100_cam4_rcp45.xml
  components/eam/bld/namelist_files/use_cases/waccm_2005-2100_cam4_rcp85.xml
  components/eam/bld/namelist_files/use_cases/waccm_sc_2000_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccmx_1996_cam4.xml
  components/eam/bld/namelist_files/use_cases/waccmx_2000_cam4.xml
  components/eam/cime_config/config_component.xml
  components/eam/cime_config/config_compsets.xml
  components/eam/cime_config/testdefs/testmods_dirs/eam/gust_export/shell_commands
  components/eam/cime_config/testdefs/testmods_dirs/eam/gust_param/shell_commands
  components/elm/bld/namelist_files/namelist_defaults.xml
Labels: Atmosphere, compset

#4535 Reset grid and compset for F2010 tests with RRM
  cime_config/tests.py
Labels: bug fix PR, BFB

#4539 Change compset name for build test
  .circleci/run.sh
Labels: Testing

#4518 add land ice logical to avoid allocation errors
  components/mpas-ocean/src/shared/Makefile
  components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F
  components/mpas-ocean/src/shared/mpas_ocn_surface_land_ice_fluxes.F
Labels: mpas-ocean, bug fix PR, BFB

#4523 Fix extra coupler restart read and add more log info
  driver-mct/main/cime_comp_mod.F90
  driver-mct/main/seq_io_mod.F90
Labels: Coupler

#4322 Add support for land on bi-grid ne1024pg2_oRRS18to6v3
  cime_config/config_grids.xml
  components/elm/bld/namelist_files/namelist_defaults.xml
  components/elm/bld/namelist_files/namelist_definition.xml
  components/elm/cime_config/config_component.xml
  components/elm/cime_config/config_compsets.xml
  components/elm/src/cpl/lnd_comp_mct.F90
  components/elm/src/main/elm_instance.F90
  components/elm/src/main/ncdio_pio.F90.in
Labels: enhancement, Land, Do not merge, HighRes

#4543 Update simyr2010 lnd surfdata map for ne30pg2 and ne1024pg2
  components/elm/bld/namelist_files/namelist_defaults.xml
Labels: BFB

#4541 Change default layout for ne30pg2_oECv3 F-cases on anvil
  cime_config/allactive/config_pesall.xml
Labels: Scripts, bug fix PR, Anvil, Testing

#4500 Add timers to EAM to provide context to SCORPIO timers
  components/eam/src/control/cam_comp.F90
  components/eam/src/control/cam_restart.F90
  components/eam/src/control/startup_initialconds.F90
  components/eam/src/cpl/atm_comp_mct.F90
  components/eam/src/dynamics/se/dyn_comp.F90
  components/eam/src/dynamics/se/inidat.F90
  components/eam/src/dynamics/se/inital.F90
  components/eam/src/dynamics/se/restart_dynamics.F90
  components/eam/src/physics/cam/physpkg.F90
  components/eam/src/physics/cam/restart_physics.F90
Labels: enhancement, Atmosphere, BFB, SCORPIO, performance

#4400 removal of one paired #ifndef CPL_BYPASS ... #endif in driver-mct/main/cime_comp.mod.F90
  driver-mct/main/cime_comp_mod.F90
Labels: Land, Coupler

#4536 Corrects the initial states for water budgets
  components/elm/src/biogeophys/WaterBudgetMod.F90
Labels: Land

#4544 Remove extra history write and reorg
  driver-mct/main/cime_comp_mod.F90
Labels: Coupler

#4530 Updates Intel's compiler version of PNNL cluster Constance
  cime_config/machines/config_machines.xml
Labels: Machine Files, BFB

#4555 For Cori, update cmake version to avoid module error at setup (maint-1.2)
  cime/config/e3sm/machines/config_machines.xml
Labels: maint-1.2

#4554 For Cori, update version for cmake to avoid module error at setup
  cime/config/e3sm/machines/config_machines.xml
Labels: maint-1.0

#4556 Update low-res WC pelayouts on Anvil
  cime_config/allactive/config_pesall.xml
Labels: Machine Files, BFB, Anvil

#4550 For Cori, update cmake module version
  cime_config/machines/config_machines.xml
Labels: Machine Files, Cori

#4502 Update the software environment and compiler versisons on Summit
  cime_config/machines/config_compilers.xml
  cime_config/machines/config_machines.xml
Labels: Machine Files, BFB, Summit

#4521 Add ocean conservation analysis member
  components/mpas-ocean/bld/build-namelist
  components/mpas-ocean/bld/build-namelist-section
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml
  components/mpas-ocean/cime_config/buildnml
  components/mpas-ocean/driver/ocn_comp_mct.F
  components/mpas-ocean/src/Registry.xml
  components/mpas-ocean/src/analysis_members/Makefile
  components/mpas-ocean/src/analysis_members/Registry_analysis_members.xml
  components/mpas-ocean/src/analysis_members/Registry_conservation_check.xml
  components/mpas-ocean/src/analysis_members/mpas_ocn_analysis_driver.F
  components/mpas-ocean/src/analysis_members/mpas_ocn_conservation_check.F
  components/mpas-ocean/src/mode_forward/mpas_ocn_forward_mode.F
  components/mpas-ocean/src/ocean.cmake
  components/mpas-ocean/src/shared/mpas_ocn_diagnostics.F
  components/mpas-ocean/src/shared/mpas_ocn_surface_bulk_forcing.F
Labels: mpas-ocean, BFB, NML

#4561 Add timers to driver-mct to provide context to SCORPIO timers
  driver-mct/main/cime_comp_mod.F90
  driver-mct/main/component_mod.F90
Labels: enhancement, bug fix PR, Coupler, performance

#4567 Convert V1 benchmarking tests from 5-day SMS to 20-day PFS tests
  cime/config/e3sm/tests.py
Labels: BFB, performance

#4566 Update README etc for v2
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: Documentation

#4552 add CFC11, CFC12 tracers
  components/mpas-ocean/bld/build-namelist
  components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
  components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml
  components/mpas-ocean/driver/ocn_comp_mct.F
  components/mpas-ocean/src/mode_forward/mpas_ocn_forward_mode.F
  components/mpas-ocean/src/ocean.cmake
  components/mpas-ocean/src/shared/Makefile
  components/mpas-ocean/src/shared/mpas_ocn_tendency.F
  components/mpas-ocean/src/shared/mpas_ocn_tracer_CFC.F
  components/mpas-ocean/src/tracer_groups/Registry_CFC.xml
  components/mpas-ocean/src/tracer_groups/Registry_tracers.xml
Labels: enhancement, mpas-ocean, BFB, NML, BGC

#4485 Update MMF Configuration to Optimize Performance
  components/eam/bld/namelist_files/namelist_defaults_eam.xml
  components/eam/cime_config/config_component.xml
Labels: Atmosphere, non-BFB, MMF
