Repository E3SM-Project/E3SM, pull requests merged in 2024-02, with the labels that each got.

#6168 remove seq_flds dependency for mpas_moabmesh
  components/mpas-framework/Makefile
  components/mpas-framework/src/driver/mpas_subdriver.F
  components/mpas-framework/src/framework/mpas_moabmesh.F
  components/mpas-ocean/driver/ocn_comp_mct.F
  components/mpas-seaice/driver/ice_comp_mct.F
Labels: mpas-ocean, mpas-seaice, bug fix PR, BFB, mpas-framework

#6146 Fixing a bug causing floating-point error in RtmMod.F90
  components/mosart/src/riverroute/RtmMod.F90
Labels: bug fix PR, BFB, River

#6200 CPL: Fix uninitialized variable.
  driver-mct/main/seq_nlmap_mod.F90
Labels: bug fix PR, BFB

#6216 SMP_PRESENT is gone, use BUILD_THREADED
  cime_config/machines/config_machines.xml
Labels: Machine Files, BFB

#6074 Add wetting and drying capability to local time-stepping scheme
  components/mpas-ocean/src/mode_forward/mpas_ocn_time_integration_lts.F
  components/mpas-ocean/src/mode_forward/mpas_ocn_time_integration_rk4.F
  components/mpas-ocean/src/shared/mpas_ocn_tidal_forcing.F
  components/mpas-ocean/src/shared/mpas_ocn_wetting_drying.F
Labels: BFB, MPAS-Ocean standalone

#6193 Fix OpenMP support for MPAS standalone builds with cray-cray
  components/mpas-framework/Makefile
Labels: BFB, mpas-framework, Frontier

#6227 Provenance: do not crash if config_src does not exist
  cime_config/customize/provenance.py
Labels: BFB, provenance

#6206 Fix restart error on maint-2.0
  cime_config/testmods_dirs/allactive/wcprodssp/user_nl_elm
  components/elm/src/data_types/ColumnDataType.F90
Labels: Land, bug fix PR, maint-2.0

#6115 Add ALCF Polaris to E3SM machines
  cime_config/machines/cmake_macros/gnu_polaris.cmake
  cime_config/machines/cmake_macros/gnugpu_polaris.cmake
  cime_config/machines/cmake_macros/nvidia_polaris.cmake
  cime_config/machines/cmake_macros/nvidiagpu_polaris.cmake
  cime_config/machines/config_batch.xml
  cime_config/machines/config_machines.xml
Labels: Machine Files, BFB, Ready to merge

#6219 Fixes a I1850ELMCN test
  components/elm/cime_config/testdefs/testmods_dirs/elm/qian_1948/user_nl_elm
Labels: Land, bug fix PR, BFB

#6231 add first patch of cime tests to public CI
  .github/workflows/e3sm-gh-ci-cime-tests.yml
Labels: Testing

#6221 Adding IcoswISC30E3r5 ice initial condition with DIB
  cime_config/tests.py
  components/mpas-seaice/cime_config/buildnml
Labels: mpas-seaice, BFB, Coupled Model, Testing

#6015 PAM variance transport
  components/eam/src/physics/crm/crm_physics.F90
  components/eam/src/physics/crm/pam/pam_driver.cpp
  components/eam/src/physics/crm/pam/pam_variance_transport.h
Labels: Atmosphere, BFB, Stealth, MMF

#6246 add instructions for docs development
  README.md
  docs/index.md
  mkdocs.yaml
Labels: Documentation

#6202 Update resolutions and maps in test suites and v3 low res mesh
  cime_config/allactive/config_pesall.xml
  cime_config/config_grids.xml
  cime_config/testmods_dirs/allactive/nlmaps/shell_commands
  cime_config/testmods_dirs/allactive/wcprodssp/shell_commands
  cime_config/testmods_dirs/allactive/wcprodssp/user_nl_elm
  cime_config/testmods_dirs/config_pes_tests.xml
  cime_config/tests.py
  components/eam/cime_config/config_pes.xml
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetahy_ftype0/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetahy_ftype1/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetahy_ftype2/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetahy_ftype4/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetahy_sl/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetanh_ftype0/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetanh_ftype1/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetanh_ftype2/user_nl_eam
  components/eam/cime_config/testdefs/testmods_dirs/eam/thetanh_ftype4/user_nl_eam
  components/elm/bld/namelist_files/use_cases/2015-2100_SSP370_transient.xml
  components/elm/bld/namelist_files/use_cases/2015-2100_SSP585_transient.xml
  components/elm/cime_config/testdefs/testmods_dirs/elm/disableDynpftCheck/user_nl_elm
  components/mpas-ocean/cime_config/testdefs/testmods_dirs/mpaso/jra_1958/shell_commands
  driver-mct/cime_config/config_component.xml
Labels: Testing

#6265 Update test-PEs for ne30+Icos WCYCL cases on Chrysalis
  cime_config/testmods_dirs/config_pes_tests.xml
Labels: Machine Files, NML, Testing, Chrysalis

#6252 Update EAM case descriptions
  components/eam/cime_config/config_component.xml
Labels: BFB

#6260 Fix ncol/pcols mismatch on interpolating aerosol mass fields to pressure levels
  components/eam/src/chemistry/mozart/mo_chm_diags.F90
Labels: Atmosphere, bug fix PR

#6247 Add testmods to instruct cases to change where it reads inputdata (ie DIN_LOC)
  cime_config/testmods_dirs/dinloc/case/shell_commands
  cime_config/testmods_dirs/dinloc/scratch/shell_commands
Labels: Machine Files, BFB

#6269 For pm-cpu (as well as gcp12, muller-cpu) use 2 nodes instead of 1 for conusx4v1pg2_r05_IcoswISC30E3r5.F2010
  components/eam/cime_config/config_pes.xml
Labels: Machine Files, BFB, GCP, pm-cpu

#6253 Changes the default setting for `rof_heat`
  driver-mct/cime_config/namelist_definition_drv.xml
  driver-moab/cime_config/namelist_definition_drv.xml
Labels: BFB, NML, River
